SELECT * FROM spring_db.Course;

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MTH200", "Mathematics", "Discrete Mathematics", 4, "In this course, you will learn about Discrete Mathematics. It is described as the study of mathematical structures that are fundamentally discrete rather than continuous.", "MTH150, MTH190");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values  ("MTH220", "Mathematics", "Linear Algebra", 4, "Linear algebra is the branch of mathematics concerning linear equations such as linear maps and their representations in vector spaces and through matrices. Linear algebra is central to almost all areas of mathematics.", "MTH150, MTH190 or MTH200");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MTH250", "Mathematics", "Calculus III", 4, "Calculus III covers multivariable calculus. In this course you will learn more about vectors and the geometry of 3-space, vector functions, multiple integrals, vector calculus and partial derivives.", "MTH200, MTH220");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SOC300", "Sociology", "Lesbian Goats and their Mannerisms", 4, "We examine how animals are socially constructed, which will challenge traditional representations of nonhuman animals, and study animals as minded social actors. It will apply sociological approaches to the study of human-animal relationships, and animal-animal relationships.", "SOC220, SOC230, SOC250");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ECN220", "Economics", "Intro to Microeconomics", 4, "Intro to Microeconomics studies the decisions of individuals and firms to allocate resources of production, exchange, and consumption. We deal with prices and production in single markets and the interaction between different markets in comparison to the study of economy-wide aggregates in macroeconomics.", "ECO150, MTH150");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("BMX100", "Biomathematics", "Frontiers in Biomathematics", 2, "Mathematical and theoretical biology is a branch of biology which employs theoretical analysis, mathematical models and abstractions of the living organisms to investigate the principles that govern the structure, development and behavior of the systems.", "BIO100, BIO150, MTH200");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MUS180", "Music", "Chamber Ensembles", 1, "Chamber music is a form of classical music that is composed for a small group of instruments—traditionally a group that could fit in a palace chamber. You will be assigned to a piece and an ensemble and perform at the end of the semester. Getting an A depends on the instructor of this course.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("PSY220", "Psychology", "Physiology of Behavior", 4, "We study the dynamic interaction between biology and behavior, with focus on how neurological cells, and biomolecules carry out the chemical and physical functions in a living system and case studies comparing these functions with behavior.", "MTH150, BIO150");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ATB100", "Astrobiology", "Introduction to Astrobiology", 5, "In this course, we discuss the exploration of life outside of Earth and to the investigation of the origin and early evolution of life on Earth.", "BIO100");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MUS220", "Music", "Beatles, Popular Music and Society", 4, "We examine the significance of the music of The Beatles in the construction of identities, audiences, ethnicities and industries, and localities.", "MUS150, MUS200");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MUS250", "Music", "Thinking about Music", 4, "An introduction to the philosophy of music. Examines the nature of music and traces the history of music philosophy from ancient Greece to the twentieth century. Lewis Rowell's Thinking About Music is more than an introduction to the connections between music and other arts, and the philosophical underpinnings of aesthetics. ", "MUS150, MUS200");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("AMS250", "American Studies", "Canadians and Who They Are", 4, "This course seeks to provide the student with an understanding of Canada. Topics include: Canadian History, Canadian Culture, Canadian Literature and U.S.-Canadian Relations", "SOC150, AMS220 or AMS250");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SWG300", "Study of Women and Gender", "Sexuality 101", 4, "We explore the historical, political, biological, cultural, sociological, educational, legal, health, aesthetic, and psychological contexts of human sexuality. Topics include: Primate Sexuality, Visual Representations of LGBT Subjects, Sex and Gender in the Ancient World, Gender, Sexuality and Religion, Love, Sex, and Relationships, History of Modern Sexualities, Sexudescriptionality and Sport", "SOC200 or SOC220, SOC250");


insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MTH405", "Mathematics", "Philosophy of Mathematics", 4, "The philosophy of mathematics is the branch of philosophy that studies the assumptions, foundations, and implications of mathematics. It aims to understand the nature and methods of mathematics, and find out the place of mathematics in people's lives.", "MTH370, LOG100, or PHI380");

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MTH150", "Mathematics", "Calculus I", 4, "An introduction to the mathematical study of continuous change. Main focus is on differential calculus concerning instantaneous rates of change and the slopes of curves. In mathematics education, calculus denotes courses of elementary mathematical analysis, which are mainly devoted to the study of functions and limits. ", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("MTH400", "Mathematics", "Abstract Algebra", 4, "The study of algebraic structures. Algebraic structures include groups, rings, fields, modules, vector spaces, lattices, and algebras.", "MTH301, MTH240 and MTH235");

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SOC252", "Sociology", "Theories of Society", 4, "The study of social constructionist theory. Covers topics such as Rational Choice Theory, Structural functionalism, Social action, Conflict Theory influenced by Marx, Symbolic interaction, False necessity, and Agential realism.", "SOC230, SOC176");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SOC203", "Sociology", "Qualitative Research Methods", 4, "We study the 5 methods of qualitative research. The use of data is informed by various methodological or philosophical assumptions, as part of various methods, such as ethnography (of various kinds), discourse analysis (of various kinds), interpretative phenomenological analysis and other phenomenological methods.[1] Qualitative research methods have been used in sociology, anthropology, political science, psychology, social work, and educational research.", "SOC100");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SOC238", "Sociology", "The Corporation", 4, "Survey of the rise, diversity, and power of the capitalist corporation in global contexts, with a focus on the 20th and 21st centuries. Topics include: the corporation as legal entity and the social and cultural consequences of this status; corporations in the colonial era; relationships among corporations, states, and non-governmental organizations in Western and non-Western contexts; anti-corporate critique and response; corporate social responsibility; and race, gender, and indigeneity.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SOC145", "Sociology", "Inequality and Social Change in China", 4, "This course offers an introduction to major social and economic issues in contemporary China. It provides a survey of the ongoing reforms and the Chinese society in transition with a focus on selected policy issues. In most weeks, the first session is reserved for a lecture by the instructor or a guest lecturer, and the second session is reserved for student-led discussions of pre-circulated questions.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ECN210", "Economics", "Intro to Macroeconomics", 4, "Macroeconomics is a branch of economics dealing with the performance, structure, behavior, and decision-making of an economy as a whole. This includes regional, national, and global economies.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ECN346", "Economics", "Econometrics", 4, "Econometrics is the application of statistical methods to economic data in order to give empirical content to economic relationships.", "ECN306, ");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ECN306", "Economics", "Intermediate Microeconomics", 4, "Analysis of competitive and noncompetitive markets in terms of efficiency of resource utilization. Intermediate Microeconomics is a core economic theory course that will further a student’s ability to apply models to explain economic decision-making by individuals and firms, how markets allocate resources, how the structure of markets affects choices and social welfare, and the ways that government intervention can improve or impair the functioning of markets.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ECN275", "Economics", "Economic Development", 4, "In the economic study of the public sector, we examine economic and social development which is the process by which the economic well-being and quality of life of a nation, region, local community, or an individual are improved according to targeted goals and objectives.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ECN262", "Economics", "Game Theory and Economics", 4, "We study the classic work upon which modern-day game theory is based. What began more than sixty years ago as a modest proposal that a mathematician and an economist wrote in 1944, Princeton University Press published Theory of Games and Economic Behavior. John von Neumann and Oskar Morgenstern conceived a groundbreaking mathematical theory of economic and social organization, based on a theory of games of strategy.", "ECN210, MTH158, MTH210");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ECN305", "Economics", "Market Discipline", 4, "Market discipline refers to the obligation by banks and financial institutions to manage their stakeholders' risk in the course of their day-to-day operations. Buyers and sellers in a market are said to be constrained by market discipline in setting prices because they have strong incentives to generate revenues and avoid bankruptcy.", "ECN220, ECN240");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("CHM101", "Chemistry", "Chemistry 101", 4, "An introduction to chemistry, which is the scientific discipline involved with elements and compounds composed of atoms, molecules and ions: their composition, structure, properties, behavior and the changes they undergo during a reaction with other substances.", "");

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("CHM356", "Chemistry", "Organic Chemistry", 5, "Organic chemistry is a branch of chemistry that studies the structure, properties and reactions of organic compounds, which contain carbon in covalent bonding. Study of structure determines their chemical composition and formula.", "CHM230, CHM306");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("CHM342", "Chemistry", "Inorganic Chemistry", 5, "Inorganic chemistry deals with synthesis and behavior of inorganic and organometallic compounds. This field covers all chemical compounds except the myriad of organic compounds, which are the subjects of organic chemistry.", "CHM306, CHM330");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("CHM100", "Chemistry", "General Chemistry", 4, "General introduction to fundamental concepts, theories, and laws of chemistry, as well as the structure, properties, and methods of obtaining the chemical elements and major chemical compounds. General chemistry also touches upon the major applications of chemistry in industry and agriculture.", "");

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SWG240", "Study of Women and Gender", "Girls in the System: Gender, Youth and Justice", 4, "This interdisciplinary course will consider the issue of gender, race, sexuality, and class in the juvenile justice system. Drawing on gender and sexuality studies, criminal justice, and sociological literature, social critiques, policy papers, case law, documentary film, personal narratives, and action, we will critically examine the history of the juvenile justice system; what it means to be in “the system”; the role of “justice” in the juvenile system;", "SOC100");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SWG241", "Study of Women and Gender", "White Supremecy in the Age of Trump", 4, "This course will analyze the history, prevalence, and current manifestations of the white supremacist movement by examining ideological components, tactics and strategies, and its relationship to mainstream politics. We will also research and discuss the relationship between white supremacy and white privilege, and explore how to build a human rights movement to counter the white supremacist movement in the U.S.", "SWG227, SWG210");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SWG227", "Study of Women and Gender", "Feminist and Queer Disability Studies", 4, "In the essay “A Burst of Light: Living with Cancer,” writer-activist Audre Lorde forges pioneering connections between the work of social justice and the environmental, gendered, and healthcare inequities that circumscribe black and brown lives. This course examines contemporary feminist/queer expressive culture, writing, and theory that centrally engages the category of disability. We ask what political and social liberation might look like when able-bodiedness is no longer privileged.", "SWG150");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("SWG400", "Study of Women and Gender", "Queer Ecologies: Considering the Nature of Sexualized Identities", 4, "What is learned by reading Queer Ecologies alongside Octavia Butler’s Lilith’s Brood? What does Over the Hedge have to do with environmental racism (Hamilton)? In short, these texts ask us to consider what it means to have a racialized and sexualized identity shaped by relationships with environments. We investigate the discursive and practical connections made between marginalized peoples and nature, and knowledge gained by queering our conceptions of nature and the natural.", "SWG345, SWG358");

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ATB211", "Astrobiology", "Biosphere 2- Science for the Future of our Planet", 4, "Learn how a unique research station in the Arizona desert is used to investigate big ideas, such as how Earth systems interact, the effects of climate change, and what our future holds. Go back in time thousands of years with information locked in ancient trees, and travel into an imagined future where humans become Martians. Collect and analyze your own scientific data, discuss big questions with participants from around the world.", "ATB210, BIO135");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ATB226", "Astrobiology", "Topics in Astrobiology", 4, "Major topics of research in astrobiology today include identifying abiotic sources of organic compounds, the synthesis and function of macromolecules in the origin of life, early life and the development of increasing complexity, the co-evolution of life and environment, and identifying, exploring, and characterizing environments for habitability and biosignatures.", "ATB211, BIO167");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ATB305", "Astrobiology", "Astrobiology and the Search for Extraterrestrial Life", 4, "What is life and what are the definitions of life? What do we know about the origin of life and what are the current hypotheses for how it originated on the Earth?", "ATB254, ATB230");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ATB401", "Astrobiology", "Aliens Among Us", 4, "Is someone you know from out of this world? We examine topics including Exobiology, Habitable Worlds, and the Emerging Worlds from which they come. Exobiology supports research into the origin and early evolution of life, the potential of life to adapt to different environments, and the implications for life elsewhere. Emerging Worlds supports research that aims to understand the formation and early evolution of the Solar System.", "ATB330, ATB350 and ATB347");


insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("PSY120", "Psychology", "Intro to Psychology", 4, "Psychology is the science of mind and behavior. Psychology includes the study of conscious and unconscious phenomena, as well as feeling and thought. It is an academic discipline of immense scope.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("PSY250", "Psychology", "Experimental Psychology", 4, "Experimental psychology refers to work done by those who apply experimental methods to psychological study and the processes that underlie it. Experimental psychologists employ human participants and animal subjects to study a great many topics, including (among others) sensation & perception, memory, cognition, learning, motivation, emotion; developmental processes, social psychology, and the neural substrates of all of these.", "PSY220");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("PSY223", "Psychology", "Clinical Studies in Psychology", 4, "Clinical psychology is an integration of science, theory, and clinical knowledge for the purpose of understanding, preventing, and relieving psychologically-based distress or dysfunction and to promote subjective well-being and personal development. ", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("PSY350", "Psychology", "Abnormal Psychology", 4, "The branch of psychology that studies unusual patterns of behavior, emotion and thought, which may or may not be understood as precipitating a mental disorder. Although many behaviors could be considered as abnormal, this branch of psychology typically deals with behavior in a clinical context.", "PSY280, PSY310");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("PSY230", "Psychology", "Social Psychology", 4, " The scientific study of how the thoughts, feelings, and behaviors of individuals are influenced by the actual, imagined, and implied presence of others.", "PSY158, PSY190");

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("AMS240", "American Studies", "The 1920s and Why They Were Important", 4, "French speakers refer to the period as the 'Années Folles', emphasizing the era's social, artistic, and cultural dynamism. The economic prosperity experienced by many countries during the 1920s (especially the United States) was similar in nature to that experienced in the 1950s and 1990s.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("AMS260", "American Studies", "African American Freedom Movements in the Twentieth Century", 4, "We introduce freedom movements starting with the series of protests that began with the Montgomery bus boycott of 1955-56. It became during the following decade the most significant southern social movement of the 20th century.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("AMS300", "American Studies", "Americans and Patriotism", 4, "Also known as American Nationalism, Mark Twain put it plainly when he said, “...modern patriotism, the true patriotism, the only rational patriotism, is loyalty to the Nation all the time, loyalty to the Government when it deserves it.“", "");

insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ENG500", "English", "Classics 500", 4, "Classics or classical studies is the study of classical antiquity, and in the Western world traditionally refers to the study of Classical Greek and Roman literature in their original languages of Ancient Greek and Latin, respectively. It may also include Greco-Roman philosophy, history, and archaeology as secondary subjects. Here we will study Classic Literature and what led to their creation.", "ENG354, ENG327");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ENG223", "English", "American Literature", 4, "During moments in history and topics including abolitionism and Transcendentalism. Novels by Edgar Allen Poe, Mark Twain, political writings of Thomas Jefferson to Harriet Beecher Stowe, we cover works of literature produced by early American authors after and during the English influence.", "ENG210, ENG163");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ENG230", "English", "Shakespeare", 4, "This course will offer an introduction to Shakespeare's work through a survey of his major plays in all genres (history, comedy, tragedy, and romance) plus selected sonnets. Texts and emphasis will vary.", "ENG223, ENG210");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ENG150", "English", "Creative Writing Workshop: The Short Story", 4, "This workshop-based course focuses on the development of skills for writing poetry, short fiction, and/or creative nonfiction through a close study of the techniques involved in these forms, analysis of model literary works, and frequent writing exercises that will be workshopped.", "");
insert into spring_db.Course (course_id, department, name, credits, description, prereqs) values ("ENG301", "English", "Autobiographical Novels of Great American Leaders", 4, "Political and Great Military leaders who introduced the United States to the country it would become.", "ENG230, ENG223, or ENG275");


